# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import mbtaapi
from mbtaapi.rest import ApiException
from mbtaapi.models.vehicle_resource_relationships_trip_data import VehicleResourceRelationshipsTripData


class TestVehicleResourceRelationshipsTripData(unittest.TestCase):
    """ VehicleResourceRelationshipsTripData unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVehicleResourceRelationshipsTripData(self):
        """
        Test VehicleResourceRelationshipsTripData
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = mbtaapi.models.vehicle_resource_relationships_trip_data.VehicleResourceRelationshipsTripData()
        pass


if __name__ == '__main__':
    unittest.main()
