# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import mbtaapi
from mbtaapi.rest import ApiException
from mbtaapi.models.facility_resource_relationships_alternates import FacilityResourceRelationshipsAlternates


class TestFacilityResourceRelationshipsAlternates(unittest.TestCase):
    """ FacilityResourceRelationshipsAlternates unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFacilityResourceRelationshipsAlternates(self):
        """
        Test FacilityResourceRelationshipsAlternates
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = mbtaapi.models.facility_resource_relationships_alternates.FacilityResourceRelationshipsAlternates()
        pass


if __name__ == '__main__':
    unittest.main()
