# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import mbtaapi
from mbtaapi.rest import ApiException
from mbtaapi.apis.stop_api import StopApi


class TestStopApi(unittest.TestCase):
    """ StopApi unit test stubs """

    def setUp(self):
        self.api = mbtaapi.apis.stop_api.StopApi()

    def tearDown(self):
        pass

    def test_api_web_stop_controller_index(self):
        """
        Test case for api_web_stop_controller_index

        
        """
        pass

    def test_api_web_stop_controller_show(self):
        """
        Test case for api_web_stop_controller_show

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
