# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import mbtaapi
from mbtaapi.rest import ApiException
from mbtaapi.models.trip_resource_relationships_shape import TripResourceRelationshipsShape


class TestTripResourceRelationshipsShape(unittest.TestCase):
    """ TripResourceRelationshipsShape unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTripResourceRelationshipsShape(self):
        """
        Test TripResourceRelationshipsShape
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = mbtaapi.models.trip_resource_relationships_shape.TripResourceRelationshipsShape()
        pass


if __name__ == '__main__':
    unittest.main()
