# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import mbtaapi
from mbtaapi.rest import ApiException
from mbtaapi.models.not_found_errors import NotFoundErrors


class TestNotFoundErrors(unittest.TestCase):
    """ NotFoundErrors unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotFoundErrors(self):
        """
        Test NotFoundErrors
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = mbtaapi.models.not_found_errors.NotFoundErrors()
        pass


if __name__ == '__main__':
    unittest.main()
