# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import mbtaapi
from mbtaapi.rest import ApiException
from mbtaapi.models.vehicle_resource_relationships_stop_links import VehicleResourceRelationshipsStopLinks


class TestVehicleResourceRelationshipsStopLinks(unittest.TestCase):
    """ VehicleResourceRelationshipsStopLinks unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVehicleResourceRelationshipsStopLinks(self):
        """
        Test VehicleResourceRelationshipsStopLinks
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = mbtaapi.models.vehicle_resource_relationships_stop_links.VehicleResourceRelationshipsStopLinks()
        pass


if __name__ == '__main__':
    unittest.main()
