# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class StopResourceAttributes(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'wheelchair_boarding': 'int',
        'name': 'str',
        'longitude': 'float',
        'latitude': 'float'
    }

    attribute_map = {
        'wheelchair_boarding': 'wheelchair_boarding',
        'name': 'name',
        'longitude': 'longitude',
        'latitude': 'latitude'
    }

    def __init__(self, wheelchair_boarding=None, name=None, longitude=None, latitude=None):
        """
        StopResourceAttributes - a model defined in Swagger
        """

        self._wheelchair_boarding = None
        self._name = None
        self._longitude = None
        self._latitude = None

        if wheelchair_boarding is not None:
          self.wheelchair_boarding = wheelchair_boarding
        if name is not None:
          self.name = name
        if longitude is not None:
          self.longitude = longitude
        if latitude is not None:
          self.latitude = latitude

    @property
    def wheelchair_boarding(self):
        """
        Gets the wheelchair_boarding of this StopResourceAttributes.
        Whether there are any vehicles with wheelchair boarding or paths to stops that are wheelchair acessible: 0, 1, 2.  Wheelchair boarding (`*/attributes/wheelchair_boarding`) corresponds to [GTFS wheelchair_boarding](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt). The MBTA handles parent station inheritance itself, so value can be treated simply:  | Value | Meaning                                       | |-------|-----------------------------------------------| | `0`   | No Information                                | | `1`   | Accessible (if trip is wheelchair accessible) | | `2`   | Inaccessible                                  |  

        :return: The wheelchair_boarding of this StopResourceAttributes.
        :rtype: int
        """
        return self._wheelchair_boarding

    @wheelchair_boarding.setter
    def wheelchair_boarding(self, wheelchair_boarding):
        """
        Sets the wheelchair_boarding of this StopResourceAttributes.
        Whether there are any vehicles with wheelchair boarding or paths to stops that are wheelchair acessible: 0, 1, 2.  Wheelchair boarding (`*/attributes/wheelchair_boarding`) corresponds to [GTFS wheelchair_boarding](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt). The MBTA handles parent station inheritance itself, so value can be treated simply:  | Value | Meaning                                       | |-------|-----------------------------------------------| | `0`   | No Information                                | | `1`   | Accessible (if trip is wheelchair accessible) | | `2`   | Inaccessible                                  |  

        :param wheelchair_boarding: The wheelchair_boarding of this StopResourceAttributes.
        :type: int
        """

        self._wheelchair_boarding = wheelchair_boarding

    @property
    def name(self):
        """
        Gets the name of this StopResourceAttributes.
        Name of a stop or station in the local and tourist vernacular.  See [GTFS `stops.txt` `stop_name](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt) 

        :return: The name of this StopResourceAttributes.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this StopResourceAttributes.
        Name of a stop or station in the local and tourist vernacular.  See [GTFS `stops.txt` `stop_name](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt) 

        :param name: The name of this StopResourceAttributes.
        :type: str
        """

        self._name = name

    @property
    def longitude(self):
        """
        Gets the longitude of this StopResourceAttributes.
        Longitude of the stop or station. Degrees East, in the [WGS-84](https://en.wikipedia.org/wiki/World_Geodetic_System#Longitudes_on_WGS.C2.A084) coordinate system. See [GTFS `stops.txt` `stop_lon`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt). 

        :return: The longitude of this StopResourceAttributes.
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """
        Sets the longitude of this StopResourceAttributes.
        Longitude of the stop or station. Degrees East, in the [WGS-84](https://en.wikipedia.org/wiki/World_Geodetic_System#Longitudes_on_WGS.C2.A084) coordinate system. See [GTFS `stops.txt` `stop_lon`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt). 

        :param longitude: The longitude of this StopResourceAttributes.
        :type: float
        """

        self._longitude = longitude

    @property
    def latitude(self):
        """
        Gets the latitude of this StopResourceAttributes.
        Latitude of the stop or station.  Degrees North, in the [WGS-84](https://en.wikipedia.org/wiki/World_Geodetic_System#A_new_World_Geodetic_System:_WGS.C2.A084) coordinate system. See [GTFS `stops.txt` `stop_lat`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt). 

        :return: The latitude of this StopResourceAttributes.
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """
        Sets the latitude of this StopResourceAttributes.
        Latitude of the stop or station.  Degrees North, in the [WGS-84](https://en.wikipedia.org/wiki/World_Geodetic_System#A_new_World_Geodetic_System:_WGS.C2.A084) coordinate system. See [GTFS `stops.txt` `stop_lat`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#stopstxt). 

        :param latitude: The latitude of this StopResourceAttributes.
        :type: float
        """

        self._latitude = latitude

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, StopResourceAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
