# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TripResource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'relationships': 'TripResourceRelationships',
        'links': 'object',
        'id': 'str',
        'attributes': 'TripResourceAttributes'
    }

    attribute_map = {
        'type': 'type',
        'relationships': 'relationships',
        'links': 'links',
        'id': 'id',
        'attributes': 'attributes'
    }

    def __init__(self, type=None, relationships=None, links=None, id=None, attributes=None):
        """
        TripResource - a model defined in Swagger
        """

        self._type = None
        self._relationships = None
        self._links = None
        self._id = None
        self._attributes = None

        if type is not None:
          self.type = type
        if relationships is not None:
          self.relationships = relationships
        if links is not None:
          self.links = links
        if id is not None:
          self.id = id
        if attributes is not None:
          self.attributes = attributes

    @property
    def type(self):
        """
        Gets the type of this TripResource.
        The JSON-API resource type

        :return: The type of this TripResource.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this TripResource.
        The JSON-API resource type

        :param type: The type of this TripResource.
        :type: str
        """

        self._type = type

    @property
    def relationships(self):
        """
        Gets the relationships of this TripResource.

        :return: The relationships of this TripResource.
        :rtype: TripResourceRelationships
        """
        return self._relationships

    @relationships.setter
    def relationships(self, relationships):
        """
        Sets the relationships of this TripResource.

        :param relationships: The relationships of this TripResource.
        :type: TripResourceRelationships
        """

        self._relationships = relationships

    @property
    def links(self):
        """
        Gets the links of this TripResource.

        :return: The links of this TripResource.
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links):
        """
        Sets the links of this TripResource.

        :param links: The links of this TripResource.
        :type: object
        """

        self._links = links

    @property
    def id(self):
        """
        Gets the id of this TripResource.
        The JSON-API resource ID

        :return: The id of this TripResource.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this TripResource.
        The JSON-API resource ID

        :param id: The id of this TripResource.
        :type: str
        """

        self._id = id

    @property
    def attributes(self):
        """
        Gets the attributes of this TripResource.

        :return: The attributes of this TripResource.
        :rtype: TripResourceAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """
        Sets the attributes of this TripResource.

        :param attributes: The attributes of this TripResource.
        :type: TripResourceAttributes
        """

        self._attributes = attributes

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TripResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
