# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class VehicleResourceRelationships(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'trip': 'VehicleResourceRelationshipsTrip',
        'stop': 'VehicleResourceRelationshipsStop',
        'route': 'VehicleResourceRelationshipsRoute'
    }

    attribute_map = {
        'trip': 'trip',
        'stop': 'stop',
        'route': 'route'
    }

    def __init__(self, trip=None, stop=None, route=None):
        """
        VehicleResourceRelationships - a model defined in Swagger
        """

        self._trip = None
        self._stop = None
        self._route = None

        if trip is not None:
          self.trip = trip
        if stop is not None:
          self.stop = stop
        if route is not None:
          self.route = route

    @property
    def trip(self):
        """
        Gets the trip of this VehicleResourceRelationships.

        :return: The trip of this VehicleResourceRelationships.
        :rtype: VehicleResourceRelationshipsTrip
        """
        return self._trip

    @trip.setter
    def trip(self, trip):
        """
        Sets the trip of this VehicleResourceRelationships.

        :param trip: The trip of this VehicleResourceRelationships.
        :type: VehicleResourceRelationshipsTrip
        """

        self._trip = trip

    @property
    def stop(self):
        """
        Gets the stop of this VehicleResourceRelationships.

        :return: The stop of this VehicleResourceRelationships.
        :rtype: VehicleResourceRelationshipsStop
        """
        return self._stop

    @stop.setter
    def stop(self, stop):
        """
        Sets the stop of this VehicleResourceRelationships.

        :param stop: The stop of this VehicleResourceRelationships.
        :type: VehicleResourceRelationshipsStop
        """

        self._stop = stop

    @property
    def route(self):
        """
        Gets the route of this VehicleResourceRelationships.

        :return: The route of this VehicleResourceRelationships.
        :rtype: VehicleResourceRelationshipsRoute
        """
        return self._route

    @route.setter
    def route(self, route):
        """
        Sets the route of this VehicleResourceRelationships.

        :param route: The route of this VehicleResourceRelationships.
        :type: VehicleResourceRelationshipsRoute
        """

        self._route = route

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, VehicleResourceRelationships):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
